### ISSUE TITLE
How to turn off ffmpeg?

### ISSUE THREAD

**Issue by opvexe** [golift/ffmpeg#1]
```
I checked your code and I found that you use exec to call ffmpeg?
I'm curious how did you turn off ffmpeg?
For example, I want to close ffmpeg after 10 seconds, did you close it in the form of kill pid?
```

**Comment by opvexe** [comment]
sove

**Comment by davidnewhall** [comment]
It's been a while since I looked at this code (I still run an app that uses it every day), but if I recall ffmpeg quits because the library passes it a max size (bytes) and a max duration (seconds), so when either of those get reached, it exits.

**Comment by shumintao** [comment]
> ffmpeg



> It's been a while since I looked at this code (I still run an app that uses it every day), but if I recall ffmpeg quits because the library passes it a max size (bytes) and a max duration (seconds), so when either of those get reached, it exits.

```
Yes, you do have time and size configured in your code, which will cause ffmpeg to exit.
```

**Comment by opvexe** [comment]
> It's been a while since I looked at this code (I still run an app that uses it every day), but if I recall ffmpeg quits because the library passes it a max size (bytes) and a max duration (seconds), so when either of those get reached, it exits.

yes, you do have time and size configured in your code, which will cause ffmpeg to exit.
I [forked](https://github.com/shumintao/ffmpeg)  your code and made some modifications as follows：

- time to control:

```
	DefaultCaptureTime = 1800 // 30 minute
	MaximumCaptureTime = 7200 // 2 hours max.
	// Deprecated: time to controle,don't need size to control.
	DefaultCaptureSize = int64(2500000) // 2.5MB default (roughly 5-10 seconds)
	// Deprecated: time to control,don't need size to control.
	MaximumCaptureSize = int64(104857600) // 100MB max.
	DefaultFFmpegPath  = "/usr/local/bin/ffmpeg"
```

- support rtmp:

```
	if !strings.Contains(input, "rtmp") {
		arg = append(arg, "-rtsp_transport", "tcp")
	}
```

- wait 
```
	log.Printf("start time: %s \n", time.Now())
	if err := cmd.Start(); err != nil {
		return cmdStr, strings.TrimSpace(out.String()), fmt.Errorf("subcommand failed: %w", err)
	}

	if err := cmd.Wait(); err != nil {
		return cmdStr, strings.TrimSpace(out.String()), fmt.Errorf("subcommand failed: %w", err)
	}
	log.Printf("end time: %s \n", time.Now())
	return cmdStr, strings.TrimSpace(out.String()), nil
```
