### ISSUE TITLE
connect error 

### ISSUE THREAD

**Issue by opvexe** [golift/ffmpeg#2]
Connection exception, no error returned

**Comment by davidnewhall** [comment]
Hello! Are you looking for help? Please share some code snippets and an explanation of what you're doing.

**Comment by opvexe** [comment]
> Hello! Are you looking for help? Please share some code snippets and an explanation of what you're doing.

```
I figured out that after 10.136.77.18live the connection is closed, I want to get ffmpeg error or corresponding. But I found that nothing corresponds. The function also blocks.
I want to get this error, how can I get it?
```


Example：

```
func main() {
	fmt.Println(time.Now())
	c := &ffmpeg.Config{
		FFMPEG: "/opt/homebrew/bin/ffmpeg",
		Audio:  true, // retain audio stream
		Time:   10,   // 10 seconds
		Width:  1920,
		Height: 1080,
		CRF:    23,
		Level:  "4.0",
		Rate:   5,
		Prof:   "baseline",
	}
	encode := ffmpeg.Get(c)
	cmd, out, err := encode.SaveVideo("rtmp://10.136.77.18/live/0", "./1.mp4", "SecuritySpyVideoTitle")

	log.Println("Command Used:", cmd)
	log.Println("Command Output:", out)
	fmt.Println(time.Now())
	if err != nil {
		log.Fatalln(err)
	}
}
````

<img width="680" alt="image" src="https://user-images.githubusercontent.com/26895243/178684441-953e0370-7358-4941-b50c-46bfaff28d14.png">

**Comment by opvexe** [comment]
> Hello! Are you looking for help? Please share some code snippets and an explanation of what you're doing.

blocking state,no error .
<img width="716" alt="image" src="https://user-images.githubusercontent.com/26895243/178684733-5b147663-d33f-4195-982f-b5e92af6adfe.png">

**Comment by davidnewhall** [comment]
Thank you for the details! I'll look into this more soon. We can make changes to make it work better in error cases.

**Comment by shumintao** [comment]
> Thank you for the details! I'll look into this more soon. We can make changes to make it work better in error cases.



```
	var out bytes.Buffer
	cmd.Stderr, cmd.Stdout = &out, &out

	log.Printf("start time: %s \n", time.Now())
	if err := cmd.Start(); err != nil {
		return cmdStr, strings.TrimSpace(out.String()), fmt.Errorf("subcommand failed: %w", err)
	}
```

**Comment by opvexe** [comment]
> Thank you for the details! I'll look into this more soon. We can make changes to make it work better in error cases.

I tried a lot of ways, but still can't get ffmpeg connection or disconnect failure halfway. can you give me some hints.

**Comment by davidnewhall** [comment]
Hello @shumintao! I made some updates. If you're still using this code, would you mind trying the linked contribution?

```
go get golift.io/ffmpeg@2c5808d
```
